swagger: "2.0"
info:
  title: twitterTrace API Documentation
  version: 1.0.0
basePath: /api
paths:
  /tweet:
    get:
      tags:
        - tweet
      summary: tweet一覧取得
      description: tweet情報の一覧を取得する
      parameters:
        - name: limit
          in: query
          description: 取得数の上限
          required: false
          type: integer
        - name: paged
          in: query
          description: 現在のページ数
          required: false
          type: integer
      responses:
        200:
          description: tweetデータ
          schema:
            type: array
            items:
              $ref: "#/definitions/Tweet1"
        404:
          description: "予期しないエラー"

  /tweet/{tweetId}:
    get:
      tags:
        - tweet
      summary: tweet詳細取得
      description: tweet情報の詳細を取得する
      parameters:
        - name: tweetId
          in: path
          description: ツイートID
          required: true
          type: integer
      responses:
        200:
          description: tweetデータ
          schema:
            $ref: "#/definitions/Tweet2"
        404:
          description: "予期しないエラー"

  /tweet/create:
    post:
      tags:
        - tweet
      summary: tweet作成
      description: tweetを作成する
      consumes:
        - multipart/form-data
      parameters:
        - in: "formData"
          name: comment_to
          type: integer
          description: コメントで投稿した場合のコメント対象のtweetId
        - in: "formData"
          name: account_name
          type: string
          description: アカウント名
        - in: "formData"
          name: body
          type: string
          description: ツイートの本文
        - in: "formData"
          name: images
          type: array
          description: ツイート画像
      responses:
        200:
          description: tweetデータ
          schema:
            $ref: "#/definitions/Tweet2"
        404:
          description: "予期しないエラー"

  /tweet/{tweet}/like:
    post:
      tags:
        - tweet
      summary: いいね操作
      description: 特定のツイート対していいねの操作を行う
      parameters:
        - name: tweetId
          in: path
          description: ツイートID
          required: true
          type: integer

      responses:
        200:
          description: tweetデータ
          schema:
            type: array
            items:
              $ref: "#/definitions/Tweet1"
        404:
          description: "予期しないエラー"

  /tweet/{tweet}/retweet:
    post:
      tags:
        - tweet
      summary: リツイート操作
      description: 特定のツイート対してリツイートの操作を行う
      parameters:
        - name: tweetId
          in: path
          description: ツイートID
          required: true
          type: integer

      responses:
        200:
          description: tweetデータ
          schema:
            type: array
            items:
              $ref: "#/definitions/Tweet1"
        404:
          description: "予期しないエラー"

  /register:
    post:
      tags:
        - auth
      summary: ユーザー登録
      description: ユーザーを作成する
      parameters:
        - in: body
          name: request
          schema:
            type: object
            required:
              - name
              - account_name
              - email
              - password
            properties:
              name:
                type: string
                example: "山田太郎"
                description: ユーザー名
              account_name:
                type: string
                example: "yamada"
                description: アカウント名
              email:
                type: string
                example: "yamada@example.com"
                description: メールアドレス
              password:
                type: string
                example: password
                description: パスワード
      responses:
        200:
          description: tweetデータ
          schema:
            $ref: "#/definitions/Tweet2"
        404:
          description: "予期しないエラー"

  /login:
    post:
      tags:
        - auth
      summary: ユーザーログイン
      description: ユーザーを認証する
      parameters:
        - in: body
          name: request
          schema:
            type: object
            required:
              - account_name
              - password
            properties:
              account_name:
                type: string
                example: "yamada"
                description: アカウント名
              password:
                type: string
                example: password
                description: パスワード
      responses:
        200:
          description: tweetデータ
          schema:
            $ref: "#/definitions/Tweet2"
        404:
          description: "予期しないエラー"

definitions:
  Tweet1:
    type: object
    properties:
      id:
        example: 124
      user_id:
        example: 25
      comment_to:
        example: null
      body:
        example: "投稿投稿"
      created_at:
        example: "2023-01-15T04:36:01.000000Z"
      updated_at:
        example: "2023-01-15T04:36:01.000000Z"
      comments:
        type: array
        items:
          $ref: "#/definitions/Comment"
      user:
        $ref: "#/definitions/User"
      comment_count:
        example: 1
      is_commented:
        example: true
      like_count:
        example: 1
      retweet_count:
        example: 0
      is_liked:
        example: true
      is_retweeted:
        example: false
      images:
        type: array
        items:
          $ref: "#/definitions/TweetImage"
  Tweet2:
    type: object
    properties:
      id:
        example: 124
      user_id:
        example: 25
      comment_to:
        example: null
      body:
        example: "投稿投稿"
      created_at:
        example: "2023-01-15T04:36:01.000000Z"
      updated_at:
        example: "2023-01-15T04:36:01.000000Z"
      comments:
        type: array
        items:
          example: []
      comment_count:
        example: 0
      is_commented:
        example: true
      like_count:
        example: 100
      retweet_count:
        example: 0
      is_liked:
        example: true
      is_retweeted:
        example: false
      images:
        type: array
        items:
          example: []

  Comment:
    type: object
    properties:
      id:
        type: integer
        example: 125
      user_id:
        type: integer
        example: 28
      comment_to:
        type: integer
        example: 124
      body:
        type: string
        example: "コメントコメント"
      created_at:
        type: string
        example: "2023-01-15T04:36:01.000000Z"
      updated_at:
        type: string
        example: "2023-01-15T04:36:01.000000Z"
      comments:
        type: array
        items:
          example: []
      user:
        $ref: "#/definitions/User"
      comment_count:
        type: integer
        example: 0
      is_commented:
        type: boolean
        example: false
      like_count:
        type: integer
        example: 0
      retweet_count:
        type: integer
        example: 0
      is_liked:
        type: boolean
        example: true
      is_retweeted:
        type: boolean
        example: false
      images:
        type: array
        items:
          example: []

  TweetImage:
    type: object
    properties:
      id:
        type: integer
        example: 18
      tweet_id:
        type: integer
        example: 124
      image:
        type: string
        example: "http://localhost/storage/tweets/images/c55b629365c122db04e5fc101525c7f8.png"
      created_at:
        type: string
        example: "2023-01-15T04:36:02.000000Z"
      updated_at:
        type: string
        example: "2023-01-15T04:36:02.000000Z"

  User:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: "山田太郎"
      account_name:
        type: string
        example: yamada
      avator:
        type: string
        example: null
      profile_background:
        type: string
        example: null
      introduction:
        type: string
        example: null
      birthday:
        type: string
        example: null
      web:
        type: string
        example: null
      email:
        type: string
        example: "yamada@example.com"
      email_verified_at:
        type: string
        format: date
        example: "2023-01-26T07:17:04.000000Z"
      created_at:
        type: string
        format: date
        example: "2023-01-26T07:17:04.000000Z"
      updated_at:
        type: string
        format: date
        example: "2023-01-26T07:17:04.000000Z"
      follow_count:
        type: integer
        example: 0
      follower_count:
        type: integer
        example: 0
      tweets:
        type: array
        example: []
      token:
        type: string
        example: "11|agDpJ0qbFpbi4gWH6GGJebj8wj2wvLkOpeQTBxEM"
